#+TITLE: Web App as a Short Course
#+AUTHOR: VLEAD
#+DATE: [2016-05-11 Wed]
#+PROPERTY: results output
#+PROPERTY: exports code
#+SETUPFILE: ./org-templates/level-0.org
#+options: ^:nil
#+LATEX: Literal LaTeX code for export

* Introduction
  
  This document describes building of an application by modelling the data of
  the system.  The system that is being modelled provides a login to a set of
  users to perform CRUD operations:
   
  1. View the details of a user, or,
  2. Create a user, or, 
  3. Update a the details of a user, or, 
  4. Delete a user.  

  The CRUD operations are done by wearing a role and the performance of these
  operations by a particular user is defined as a session.

* System
  A system is defined by the entities contained in it and the relationships
  between these entities. 

** Entities in the System
  The system is composed of User, Email, Name, Role
  and a Session entities.

** Relationships between the entities in the system

*** Symbol Definitions

    1. ! denotes exactly one
    2. ? denotes at most one (zero or one)
    3. + denotes at least one (one or more)
    4. > denotes a relationship
    5. [a,b] denotes both a is inverse of b
   
*** Entity Relationships

    1. [email, user] : User? > Email! :: implies 
       - email is a relation with domain as User and co-domain of exactly one
         email.  (email : User > Email!)
       - user is a relation with domain as Email and co-domain of atmost one
         User. (user: Email > User?)
       - user is inverse of email
  
*** Realization of the system  
    
#+BEGIN_SRC python :tangle src/entities.py :eval no
class User:
    
    def __init__(email, name):
        pass
#+END_SRC

#+BEGIN_SRC python :tangle src/entities.py :eval no
class Email:
    def __init__():
        pass
#+END_SRC

#+BEGIN_SRC python :tangle src/entities.py :eval no
class Name:
    def __init__():
        pass
#+END_SRC

#+BEGIN_SRC python :tangle src/entities.py :eval no
class Role:
    def __init__():
        pass
#+END_SRC

#+BEGIN_SRC python :tangle src/entities.py :eval no
class Session:
    def __init__():
        pass
#+END_SRC


* State of the system
  The state of the system is comprised of sets of *users*, *emails*, *names*,
  *roles* and *sessions*.
  
  
  

     


         
     

  
